// <auto-generated />
using System;
using DiscordBot.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240607070457_DailyVipGiftReminder")]
    partial class DailyVipGiftReminder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DiscordBot.Db.Entity.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTemplate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.DailyVipGiftReminderSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "UserId", "ReminderId");

                    b.ToTable("DailyVipGiftReminderSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GlobalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeValue")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("UlongValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildNewsOverride", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Snapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemTag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleatedMessageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "NewsId");

                    b.ToTable("GuildNewsOverrides");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("CromBasHelperChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DailyDungeonInfoChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DailyDungeonInfoMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DailyEffectChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DailyEffectMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DataScapingNewsChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ErinnTimeChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ErinnTimeMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderMessageIdBattle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderMessageIdLife")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderMessageIdMisc")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderMessageIdOneDay")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("InstanceResetReminderMessageIdToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildUserSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUserSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.InstanceReminderSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "UserId", "ReminderId");

                    b.ToTable("InstanceReminderSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Snapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemTag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DiscordBot.SemanticKernel.Plugins.KernelMemory.Extensions.Discord.DiscordDbMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "author_id");

                    b.Property<string>("AuthorUsername")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "author_username");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_id");

                    b.Property<string>("ChannelMention")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_mention");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_name");

                    b.Property<string>("ChannelTopic")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "channel_topic");

                    b.Property<string>("CleanContent")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "clean_content");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<int>("EmbedsCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "embeds_count");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "message_id");

                    b.Property<string>("ReferenceMessageId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "reference_message_id");

                    b.Property<string>("ServerDescription")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "server_description");

                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "server_id");

                    b.Property<int>("ServerMemberCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "server_member_count");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "server_name");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.DailyVipGiftReminderSetting", b =>
                {
                    b.HasOne("DiscordBot.Db.Entity.GuildUserSetting", "GuildUserSetting")
                        .WithMany("DailyVipGiftReminderSettings")
                        .HasForeignKey("GuildId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildUserSetting");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildNewsOverride", b =>
                {
                    b.HasOne("DiscordBot.Db.Entity.GuildSetting", "GuildSetting")
                        .WithMany("GuildNewsOverrides")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildSetting");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildUserSetting", b =>
                {
                    b.HasOne("DiscordBot.Db.Entity.GuildSetting", "GuildSetting")
                        .WithMany("GuildUserSettings")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildSetting");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.InstanceReminderSetting", b =>
                {
                    b.HasOne("DiscordBot.Db.Entity.GuildUserSetting", "GuildUserSetting")
                        .WithMany("InstanceReminderSettings")
                        .HasForeignKey("GuildId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildUserSetting");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildSetting", b =>
                {
                    b.Navigation("GuildNewsOverrides");

                    b.Navigation("GuildUserSettings");
                });

            modelBuilder.Entity("DiscordBot.Db.Entity.GuildUserSetting", b =>
                {
                    b.Navigation("DailyVipGiftReminderSettings");

                    b.Navigation("InstanceReminderSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
